### ISSUE TITLE
Bug with long aetheryte names

### ISSUE THREAD

**Issue by xPumaa** [NightmareXIV/Lifestream#10]
Too long names are abbreviated with "..." and for these aetherytes the teleport doesn't work

Client language: German
Region: Ishgard

**Comment by Limiana** [comment]
Hello. Yes, these have to be accounted for manually. I will do it in next update

**Comment by Limiana** [comment]
Hello! This should have been fixed few versions ago actually, if there is still this problem please reopen the issue
