### ISSUE TITLE
[Bug] World travel doesn't work in german clients

### ISSUE THREAD

**Issue by xPumaa** [NightmareXIV/Lifestream#14]
The name of the world is in the middle for german clients.

Correct version is:
```csharp
var x = (AddonSelectYesno*)Util.GetSpecificYesno(false, $"Travel to", "へ移動します、よろしいですか？", $"Nach {s} reisen?", "Voulez-vous vraiment visiter");
```

https://github.com/NightmareXIV/Lifestream/blob/4da91f9289e2ceb51029af1f3c617798f6eaddfe/Lifestream/Schedulers/WorldChange.cs#LL76C27

**Comment by Limiana** [comment]
Hello! Thank you, will be fixed soon

**Comment by Limiana** [comment]
Hello! This should have been fixed few versions ago actually, if there is still this problem please reopen the issue
