### ISSUE TITLE
[Request] Add a Cancel button to the progress bar

### ISSUE THREAD

**Issue by ZohiDev** [NightmareXIV/Lifestream#16]
I've had situations where I'll initiate a world hop, but change my mind before the teleport goes off and cancel it. This will leave the progress bar stuck (until it times out) and prevents you from initiating another world hop until its finished.

I think a simple cancel button on the progress bar could solve that. Alternatively, making it automatically cancel the hop when canceling the teleport would be a welcome fix too :)

**Comment by Limiana** [comment]
Hello! Right clicking progress bar should cancel all operation

**Comment by ZohiDev** [comment]
Oh wow you are absolutely correct, you even have a nice little tooltip for it! Very sorry for wasting your time with this. Tyvm for the quick response!
