### ISSUE TITLE
[Feature Request] Option To Set Aethernet Destination After World or DC Transfer

### ISSUE THREAD

**Issue by SelfAfflicted** [NightmareXIV/Lifestream#17]
Pretty much as the title reads, most of the time when using the travel system it's specifically for checking marketboard prices, having an option to go directly to, Sapphire Avenue Exchange, for instance, after arriving would be convenient, maybe with a modifier key to temporary block said option too for times when not needed.

**Comment by Limiana** [comment]
Added in upcoming update
