### ISSUE TITLE
[Bug] Logging in the wrong character if destination world has a character with that name

### ISSUE THREAD

**Issue by drejjmit** [NightmareXIV/Lifestream#18]
If i DC travel to a world that has a character with that name, it logs in the first character with that name, not the actual transferred character.
Same when returning with /li
Then it tries to return the first character, not the actual character that is DC traveling.

![image](https://github.com/NightmareXIV/Lifestream/assets/15526476/db43936b-25e6-4ab7-8896-7aa9aee88d22)

**Comment by Limiana** [comment]
Hello! This bug was investigated and the solution was found. It will be fixed in next version.
