### ISSUE TITLE
Changing instance

### ISSUE THREAD

**Issue by HitagiSenjougaharaFFXIV** [NightmareXIV/Lifestream#19]
Was doing hunt, when clicking on etherite to change instance. It sets the etherite as homepoint and can't do anything with the etherite (no access to the menu to change instance). need to unload lifestream and exit the game.

**Comment by Limiana** [comment]
Hello! This is weird. Please type `/xllog`, in top left corner of the window set log level to "verbose", trigger the issue and send me your log file: `%appdata%\XIVLauncher\dalamud.log`
