### ISSUE TITLE
[Feature Request] Mark aetherytes with market boards nearby

### ISSUE THREAD

**Issue by AAfetisov** [NightmareXIV/Lifestream#20]
First of all want to thank you for the addon. It's great!
Could you mark eatherytes in the list that have an mb nearby with some icon pls. It would save tons of time. Just in cities, as mbs are literally everywhere in residential areas
![image](https://github.com/NightmareXIV/Lifestream/assets/1430709/fd8b907d-fc7f-42e6-aead-ea8b84be7f08)

**Comment by Limiana** [comment]
Hello!
What about right clicking and setting destination as favorite? is it good enough for your purpose?

**Comment by Limiana** [comment]
I'd suggest that it's enough, if no please reopen issue
