### ISSUE TITLE
[Bug] Auto Confirm "Logging in with character name." When Visiting Another Data Center.

### ISSUE THREAD

**Issue by tjrawrin** [NightmareXIV/Lifestream#21]
I don't think this was an issue when I first installed the plugin. But now, for whatever reason, whenever I visit another data center. I get a dialog that I have to click OK on to continue logging in. Can Lifestream automatically confirm this dialog or is this something I need to configure though Yes Already? Sorry if this is not a bug! >.<

![dialog](https://github.com/NightmareXIV/Lifestream/assets/1529775/a353e474-1466-4152-b8e9-1fafd340492b)

**Comment by tjrawrin** [comment]
Here's the log up until I have to click OK on the dialog.

16:32:42.154 | DBG [Lifestream] [Lifestream] Beginning data center changing process. Destination: Aether, Jenova
--------------------------------
16:32:42.166 | DBG [Lifestream] [Lifestream] Starting to execute task: Remove afk
--------------------------------
16:32:42.166 | INF [Lifestream] [Lifestream] Disabling Yes Already
--------------------------------
16:32:42.182 | DBG [Lifestream] [Lifestream] Task Remove afk completed successfully
--------------------------------
16:32:42.199 | DBG [Lifestream] [Lifestream] Starting to execute task: WaitUntilNotAfk
--------------------------------
16:32:42.215 | DBG [Lifestream] [Lifestream] Task WaitUntilNotAfk completed successfully
--------------------------------
16:32:42.233 | DBG [Lifestream] [Lifestream] Starting to execute task: Waiting until player returns to home world
--------------------------------
16:32:42.249 | DBG [Lifestream] [Lifestream] Task Waiting until player returns to home world completed successfully
--------------------------------
16:32:42.266 | DBG [Lifestream] [Lifestream] Starting to execute task: Waiting until player is not busy (TaskWaitUntilInHomeWorld)
--------------------------------
16:32:42.282 | DBG [Lifestream] [Lifestream] Task Waiting until player is not busy (TaskWaitUntilInHomeWorld) completed successfully
--------------------------------
16:32:42.299 | DBG [Lifestream] [Lifestream] Starting to execute task: WaitUntilNotBusy
--------------------------------
16:32:42.316 | DBG [Lifestream] [Lifestream] Task WaitUntilNotBusy completed successfully
--------------------------------
16:32:42.333 | DBG [Lifestream] [Lifestream] Starting to execute task: Logout
--------------------------------
16:32:42.349 | DBG [Lifestream] [Lifestream] [DCChange] Sending logout command
--------------------------------
16:32:42.349 | DBG [Lifestream] [Lifestream] Task Logout completed successfully
--------------------------------
16:32:42.366 | DBG [Lifestream] [Lifestream] Starting to execute task: SelectYesLogout
--------------------------------
16:32:42.371 | DBG [YesAlready] AddonSelectYesNo.OnSetup
--------------------------------
16:32:42.533 | DBG [Lifestream] [Lifestream] [DCChange] Confirming logout
--------------------------------
16:32:42.533 | DBG [Lifestream] [Lifestream] Task SelectYesLogout completed successfully
--------------------------------
16:32:42.549 | DBG [Lifestream] [Lifestream] Starting to execute task: WaitUntilCanAutoLogin
--------------------------------
16:32:43.646 | DBG [ClientState] Is logout
--------------------------------
16:32:44.027 | DBG [Lifestream] [Lifestream] Task WaitUntilCanAutoLogin completed successfully
--------------------------------
16:32:44.043 | DBG [Lifestream] [Lifestream] Starting to execute task: TitleScreenClickStart
--------------------------------
16:32:44.060 | DBG [Lifestream] [Lifestream] [DCChange] Clicking start
--------------------------------
16:32:44.077 | DBG [Lifestream] [Lifestream] Task TitleScreenClickStart completed successfully
--------------------------------
16:32:44.122 | DBG [Lifestream] [Lifestream] Starting to execute task: OpenContextMenuForChara
--------------------------------
16:32:50.427 | DBG [Lifestream] [Lifestream] [DCChange] Opening context menu index 0
--------------------------------
16:32:50.443 | DBG [Lifestream] [Lifestream] Task OpenContextMenuForChara completed successfully
--------------------------------
16:32:50.460 | DBG [Lifestream] [Lifestream] Starting to execute task: SelectVisitAnotherDC
--------------------------------
16:32:50.627 | DBG [Lifestream] [Lifestream] [DCChange] Selecting visit another data center
--------------------------------
16:32:50.627 | DBG [Lifestream] [Lifestream] Task SelectVisitAnotherDC completed successfully
--------------------------------
16:32:50.643 | DBG [Lifestream] [Lifestream] Starting to execute task: ConfirmDcVisitIntention
--------------------------------
16:32:50.877 | DBG [Lifestream] [Lifestream] [DCChange] Confirming DC visit intention
--------------------------------
16:32:50.877 | DBG [Lifestream] [Lifestream] Task ConfirmDcVisitIntention completed successfully
--------------------------------
16:32:50.893 | DBG [Lifestream] [Lifestream] Starting to execute task: SelectTargetDataCenter
--------------------------------
16:32:52.143 | DBG [Lifestream] [Lifestream] [DCChange] Selecting Target DC Aether index 3
--------------------------------
16:32:52.143 | DBG [Lifestream] [Lifestream] AddonDKTWorldCheck_ReceiveEventDetour: 000001AA3D5E7750, 35, 0000000000000001, 0000003B405AEF20, 0000003B405AEE90
--------------------------------
16:32:52.143 | DBG [Lifestream] [Lifestream]   Event: 0000000000000000, 000001A9F1376C90, 000001A944430000, 1, 0000000000000000, ListItemToggle, 0, 0
--------------------------------
16:32:52.143 | DBG [Lifestream] [Lifestream]   Data: 0000003B405AEED0(0000003B405AEEE0), 1, 0 | 0, 0, 0, 0, 0, 0, 0, 0, 208, 238, 90, 64, 59, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
--------------------------------
16:32:52.143 | DBG [Lifestream] [Lifestream]   Data 2, 1, 0,  :00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
--------------------------------
16:32:52.143 | DBG [Lifestream] [Lifestream] AtkComponentTreeList_vf31Detour: 000001A944430000, 1, 0
--------------------------------
16:32:52.160 | DBG [Lifestream] [Lifestream] Task SelectTargetDataCenter completed successfully
--------------------------------
16:32:52.177 | DBG [Lifestream] [Lifestream] Starting to execute task: SelectTargetWorld
--------------------------------
16:32:52.327 | DBG [Lifestream] [Lifestream] [DCChange] Selecting target world Jenova index 7
--------------------------------
16:32:52.327 | DBG [Lifestream] [Lifestream] AddonDKTWorldCheck_ReceiveEventDetour: 000001AA3D5E7750, 35, 0000000000000002, 0000003B405AEF20, 0000003B405AEE90
--------------------------------
16:32:52.327 | DBG [Lifestream] [Lifestream]   Event: 0000000000000000, 000001A9F1376E50, 000001A94442F6C0, 1, 0000000000000000, ListItemToggle, 0, 0
--------------------------------
16:32:52.327 | DBG [Lifestream] [Lifestream]   Data: 0000003B405AEED0(0000003B405AEEE0), 5, 0 | 0, 0, 0, 0, 0, 0, 0, 0, 208, 238, 90, 64, 59, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
--------------------------------
16:32:52.327 | DBG [Lifestream] [Lifestream]   Data 2, 1, 4,  :00 00 00 00 01 00 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
--------------------------------
16:32:52.327 | DBG [Lifestream] [Lifestream] AtkComponentTreeList_vf31Detour: 000001A94442F6C0, 5, 0
--------------------------------
16:32:52.343 | DBG [Lifestream] [Lifestream] Task SelectTargetWorld completed successfully
--------------------------------
16:32:52.360 | DBG [Lifestream] [Lifestream] Starting to execute task: ConfirmDcVisit
--------------------------------
16:32:52.510 | DBG [Lifestream] [Lifestream] [DCChange] Confirming DC visit
--------------------------------
16:32:52.510 | DBG [Lifestream] [Lifestream] Task ConfirmDcVisit completed successfully
--------------------------------
16:32:52.527 | DBG [Lifestream] [Lifestream] Starting to execute task: ConfirmDcVisit2
--------------------------------
16:32:58.427 | DBG [Lifestream] [Lifestream] [DCChange] Confirming DC visit 2
--------------------------------
16:32:58.427 | DBG [Lifestream] [Lifestream] Task ConfirmDcVisit2 completed successfully
--------------------------------
16:32:58.444 | DBG [Lifestream] [Lifestream] Starting to execute task: SelectOk
--------------------------------
16:33:14.409 | DBG [Lifestream] [Lifestream] [DCChange] Selecting OK
--------------------------------
16:33:14.409 | DBG [Lifestream] [Lifestream] Task SelectOk completed successfully
--------------------------------
16:33:14.426 | DBG [Lifestream] [Lifestream] Starting to execute task: Wait until chara list available
--------------------------------
16:33:20.840 | DBG [Lifestream] [Lifestream] Task Wait until chara list available completed successfully
--------------------------------
16:33:20.856 | DBG [Lifestream] [Lifestream] Starting to execute task: SelectCharacter
--------------------------------
16:33:20.873 | DBG [Lifestream] [Lifestream] [DCChange] Selecting character index 0
--------------------------------
16:33:20.873 | DBG [Lifestream] [Lifestream] Task SelectCharacter completed successfully
--------------------------------
16:33:20.890 | DBG [Lifestream] [Lifestream] Starting to execute task: SelectYesLogin
--------------------------------
16:33:20.941 | DBG [YesAlready] AddonSelectYesNo.OnSetup
--------------------------------
16:33:21.123 | DBG [Lifestream] [Lifestream] [DCChange] Confirming login
--------------------------------
16:33:21.123 | DBG [Lifestream] [Lifestream] Task SelectYesLogin completed successfully
--------------------------------
16:33:21.124 | DBG [YesAlready] AddonSelectYesNo.OnSetup
--------------------------------
16:33:21.140 | DBG [Lifestream] [Lifestream] Starting to execute task: TaskWaitUntilInWorld

**Comment by Limiana** [comment]
Hello! Normally it should do so. And it does so for me. But I will check it again

**Comment by tjrawrin** [comment]
@Limiana - This might be causing the problem. I have a dialog pop, before the dialog in my original post. This first dialog is auto confirmed and then the one about "Logging in with..." comes up which isn't confirmed automatically. I have an active fanta potion on my character that I haven't used yet by editing my character.

Is there a way to check for and confirm both dialogs?

![dialog2](https://github.com/NightmareXIV/Lifestream/assets/1529775/342e5060-3c3c-406b-8a0f-051fc5062f16)

**Comment by Limiana** [comment]
> @Limiana - This might be causing the problem. I have an additional dialog pop up, before the dialog in my original post. This dialog is automatically confirmed and then the one about "Logging in with..." comes up after which is not. It's because I have an active fanta potion on my character that I haven't fully used yet by editing my character.
> 
> Is there a way to check for and confirm both dialogs?
> 
> ![dialog2](https://user-images.githubusercontent.com/1529775/276446067-342e5060-3c3c-406b-8a0f-051fc5062f16.jpg)

So you say, you get two dialogues? Under which circumstances this happens?
I'll see if I can do something to fix it

**Comment by Limiana** [comment]
I attempted to fix it in version .8, please try if it works

**Comment by tjrawrin** [comment]
Correct I get two dialogs...

- The first dialog is telling me I can re-edit my character because I have an active unused fantasia potion.
- The second dialog is the normal one that pops up when you visit another data center.

Your changes in .8 seem to have worked. I visited a couple different servers on different data centers and both dialogs were confirmed automatically.

Thank you for fixing it and thank you for this awesome useful plugin! <3
