### ISSUE TITLE
[QoL Request] Stop Lifestream window from hogging focus when it appears

### ISSUE THREAD

**Issue by jasinkare** [NightmareXIV/Lifestream#22]
Current Lifestream window behavior steals focus from other windows(including other ImGui windows like ChatTwo) when it pops up, frequently causing multiple basegame windows being opened when I'm typing in chat mid world-visit.

A toggle switch to prevent this behavior would be nice, if possible, as it causes mild headaches when trying to type teleports in chat with Teleporter.

**Comment by Limiana** [comment]
Hello! This issue has been resolved.
