### ISSUE TITLE
Option to Disable the YesAlready Disabling Or Option to automatically accept world travels

### ISSUE THREAD

**Issue by Solandus** [NightmareXIV/Lifestream#23]
When traveling to other worlds, there is still a question if you want to travel this world. I had this set in YesAlready to auto accept. As Lifestream disables YesAlready I needed to click now on the request if i really want to travel there.

I see two options to solve this:
1. Implement an option to not disable YesAlready (for people who know what they do) (the easy way)
2. Implement an option to automatically tick the ok button for world travel.

**Comment by Limiana** [comment]
Hello. The plugin is supposed to confirm all windows by itself, without using any other plugins. If it fails to do so, can you please:
- Attach a screenshot of a window where it gets stuck
- Attach log file: `%appdata%\XIVLauncher\dalamud.log` just after it gets stuck

**Comment by Solandus** [comment]
![image](https://github.com/NightmareXIV/Lifestream/assets/22271786/0c6df570-8c75-4a4e-a950-07efa291b502)

**Comment by Solandus** [comment]
![image](https://github.com/NightmareXIV/Lifestream/assets/22271786/2eabcdf3-1cbb-4510-b9d3-f4332a259e0f)

**Comment by Solandus** [comment]
[dalamud - Kopie.log](https://github.com/NightmareXIV/Lifestream/files/13196459/dalamud.-.Kopie.log)

**Comment by Solandus** [comment]
![image](https://github.com/NightmareXIV/Lifestream/assets/22271786/d1c24a2b-509d-4950-b5fc-f7c5164e9554)

**Comment by Limiana** [comment]
Thanks for your report. This issue has been resolved in version 2.0.0.9, please update the plugin
