### ISSUE TITLE
Suggestion: Cancel Party Finder Recruitment Automatically

### ISSUE THREAD

**Issue by kaizerfreak** [NightmareXIV/Lifestream#30]
When player is leader of a party that is listed in PF, the plugin gets stuck because it does not cancel party finder recruitment and thus cannot leave the party.

**Comment by Limiana** [comment]
Hello! 
Aren't you supposed to be able to move worlds even when in pf?
I will investigate this issue

**Comment by kaizerfreak** [comment]
Not when in a PF limited to world server only.

**Comment by Limiana** [comment]
Implemented in 2.3.0.6
