### ISSUE TITLE
Add command to clear action queue

### ISSUE THREAD

**Issue by bluesolei1** [NightmareXIV/Lifestream#35]
In some scenarios if you interrupt plugin it get stuck in 'another action already in progress' state with only way to fix is to re-enable plugin.

Issue mainly arises when there's multiple S ranks hunts and servers have queues.

Scenario to reproduce the issue:
1.  Use plugin to world visit
2. Cancel the world visit
3. Try to use plugin to world  other visit again

Would be good to have intended way to reset plugin action's queue instead of bruteforce  turn off and on again

**Comment by bluesolei1** [comment]
Upon further reading i've found that if plugin have progress enabled (was disabled for me), you can right click it to cancel all actions, which solves the issue.

**Comment by Limiana** [comment]
Hello!
By the way, the command is `/li stop` also
