### ISSUE TITLE
Suggestion: Specific Teleports

### ISSUE THREAD

**Issue by Battler624** [NightmareXIV/Lifestream#36]
I am wondering if its possible to give an alias to a specific location and have lifestream teleport to it.
For example, gangos. I'd write /li gangos and it would teleport to Doman Enclave and then use the aethernet to tp to gangos.

Ofcourse, the steps I would just write down or select from a list.

**Comment by karpik123** [comment]
I'd also be interested in something like this, sort of chain teleport functionality. 

For the previous expansion, I was spoiled by Sharlayan, where teleport brings you to both mb and retainer bell. Radz-at-Han was the same. In Dawntrail, both Tulilololalolal and Solution Nine require another teleport for marketboard and for tomestone/crafting stuff.

**Comment by Limiana** [comment]
Planned is a similar tab to address book where you will be able to create your own chain of teleports to execute and assign custom command to it

**Comment by Flavescent** [comment]
Thanks for planning to implement this. It would be ideal to combine this with Automaton's address book functionality to also allow for a navmesh pathing coordinate at the end of the chain.

**Comment by Fyrhtu** [comment]
Looking forward to implementation; came here to suggest a /li island shortcut, but a DIY teleports tab would handle that just fine.

**Comment by Limiana** [comment]
Added in testing version
