### ISSUE TITLE
Aethernet Teleport not functional

### ISSUE THREAD

**Issue by TheKedart** [NightmareXIV/Lifestream#38]
As of recently aethernet teleportation is not working for me.

The log shows this:
`[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] Enqueued task Remove afk/busy status
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] Enqueued task WaitForScreen
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] Enqueued task TargetValidAetheryte
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] Enqueued task InteractWithTargetedAetheryte
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] Enqueued task SelectAethernet
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] Enqueued task Delay (0ms)
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] Enqueued task TeleportToAethernetDestination
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] →Starting to execute task [Remove afk/busy status], timeout=30000
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] →→Task [Remove afk/busy status] completed successfully 
[Information@6/14/2024 7:37:47 PM -07:00] Disabling Yes Already (new)
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] →Starting to execute task [WaitForScreen], timeout=30000
[Debug@6/14/2024 7:37:47 PM -07:00] [NeoTaskManager] →→Task [WaitForScreen] completed successfully 
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →Starting to execute task [TargetValidAetheryte], timeout=30000
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →→Task [TargetValidAetheryte] completed successfully 
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →Starting to execute task [InteractWithTargetedAetheryte], timeout=30000
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →→Task [InteractWithTargetedAetheryte] completed successfully 
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →Starting to execute task [SelectAethernet], timeout=30000
[Debug@6/14/2024 7:37:48 PM -07:00] TrySelectSpecificEntry: selecting Aethernet./0 as requested by Aethernet., 都市転送網, Ätherytennetz, Réseau de transport urbain éthéré
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →→Task [SelectAethernet] completed successfully 
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →Starting to execute task [Delay (0ms)], timeout=5000
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →→Task [Delay (0ms)] completed successfully 
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →Starting to execute task [TeleportToAethernetDestination], timeout=30000
[Debug@6/14/2024 7:37:48 PM -07:00] Could not find destination The Dossal Gate, attempting partial search...
[Warning@6/14/2024 7:37:48 PM -07:00] GetAvailableAethernetDestinations does not contains The Dossal Gate, contains 
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] Inserted task <TeleportToAethernetDestination>b__2
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] Inserted task <TeleportToAethernetDestination>b__1
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →→Task [TeleportToAethernetDestination] completed successfully 
[Debug@6/14/2024 7:37:48 PM -07:00] [NeoTaskManager] →Starting to execute task [<TeleportToAethernetDestination>b__1], timeout=30000
[Verbose@6/14/2024 7:37:48 PM -07:00] Firing callback: TelepotTown, valueCount = 2, updateStatte = True, values:

[Error@6/14/2024 7:37:48 PM -07:00] The type initializer for 'ECommons.Automation.Callback' threw an exception.
   at ECommons.Automation.Callback.FireRaw(AtkUnitBase* Base, Int32 valueCount, AtkValue* values, Byte updateState) in D:\VS\Lifestream\ECommons\ECommons\Automation\Callback.cs:line 80
   at ECommons.Automation.Callback.Fire(AtkUnitBase* Base, Boolean updateState, Object[] values) in D:\VS\Lifestream\ECommons\ECommons\Automation\Callback.cs:line 137
   at ECommons.Automation.NeoTaskManager.TaskManagerTask.<>c__DisplayClass14_0.<.ctor>b__0() in D:\VS\Lifestream\ECommons\ECommons\Automation\NeoTaskManager\TaskManagerTask.cs:line 29
   at ECommons.Automation.NeoTaskManager.TaskManager.Tick(Object framework) in D:\VS\Lifestream\ECommons\ECommons\Automation\NeoTaskManager\TaskManager.cs:line 167
[Information@6/14/2024 7:37:48 PM -07:00] Enabling Yes Already (new)`

**Comment by Limiana** [comment]
Hello! type `/xlbranch` and check that you're using "release" branch
