### ISSUE TITLE
Feature Request: Print a log message about where the plugin is bringing you.

### ISSUE THREAD

**Issue by coredumperror** [NightmareXIV/Lifestream#39]
It'd be really nice if typing `/li gob` would print out a message saying "Transferring you to the Goblin server in the Crystal data center." Or something along those lines. 

It'd be useful to know for sure that the abbreviation you typed is leading you to the right place, giving you time to cancel in case you mistyped.

**Comment by Limiana** [comment]
Added in next update

**Comment by coredumperror** [comment]
Awesome, thanks!
