### ISSUE TITLE
Instance menu

### ISSUE THREAD

**Issue by Iniquity1** [NightmareXIV/Lifestream#43]
Is it possible to have the instance menu persist while map is open? It would be a nice upgrade for hunts as you can look at where the next target is while TPing/swapping instances.

**Comment by Limiana** [comment]
You can configure now which windows will hide Lifestream overlays
Go to Lifestream - Settings - Overlay, and remove "AreaMap" from "Game window integration" section

**Comment by Iniquity1** [comment]
Thanks so much for the work! Works like a charm.
