### ISSUE TITLE
Create static pathes for grand companies instead of relying on navmesh

### ISSUE THREAD

**Issue by Fluffdad** [NightmareXIV/Lifestream#46]
It wont get out of the stairs I don't think it's actually waiting to see if it arrives anywhere since the 3 movement queues just instantly complete the attempts to straight line for the desk. For adder it doesn't even attempt to leave the aetheryte 

Immortal Flame
> [7/19/2024 1:16:42 AM -05:00] Enabling Yes Already (new)
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] Enqueued task <Enqueue>b__1
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →Starting to execute task [<Enqueue>b__1], timeout=30000
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] Enqueued task IsReady> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] Enqueued task Build path and check
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →→Task [<Enqueue>b__1] completed successfully 
> [7/19/2024 1:18:07 AM -05:00] Disabling Yes Already (new)
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →Starting to execute task [IsReady], timeout=30000
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →→Task [IsReady] completed successfully 
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →Starting to execute task [Build path and check], timeout=30000
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] Enqueued task UseSprint
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] Enqueued task <Enqueue>b__5
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →→Task [Build path and check] completed successfully 
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →Starting to execute task [UseSprint], timeout=30000
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →→Task [UseSprint] completed successfully 
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →Starting to execute task [<Enqueue>b__5], timeout=30000
> [7/19/2024 1:18:07 AM -05:00] [NeoTaskManager] →→Task [<Enqueue>b__5] completed successfully 
> [7/19/2024 1:18:07 AM -05:00] Enabling Yes Already (new)

**Comment by Limiana** [comment]
Hey, do you have vnavmesh installed? That's required for it to do pathing
`https://puni.sh/api/repository/veyn` is the repo

**Comment by Grammernatzi** [comment]
> Hey, do you have vnavmesh installed? That's required for it to do pathing `https://puni.sh/api/repository/veyn` is the repo

Is this explained anywhere in the readme/description/config? I was having the same error and didn't figure out how to solve it until now.

**Comment by shinji257** [comment]
I'll note that I didn't know vnavmesh would be a requirement until I was mucking around with GatherBuddy Reborn and noticed that it going back home actually worked via lifestream.

**Comment by Limiana** [comment]
Added a note on main page, in future though I'll be switching it to use constant pathes
