### ISSUE TITLE
Fix Aethernet Shard menu shows when option is disabled

### ISSUE THREAD

**Issue by Evolutious** [NightmareXIV/Lifestream#50]
Hi! I currently have Aethernet menu disabled in the Overlay settings (see image) but when I am near an Aethernet shard, I have a small box showing that looks to be the Aethernet menu just not being populated since that module is disabled. Any way to prevent this from showing?

![Screenshot 2024-08-14 095815](https://github.com/user-attachments/assets/873cc6f3-0ab6-4e5d-a90b-feb5f7e96fc5)
![Screenshot 2024-08-14 100053](https://github.com/user-attachments/assets/a068858a-8173-4ac9-86bb-1991f771dc9f)

**Comment by Limiana** [comment]
Should be fixed in testing version
