### ISSUE TITLE
Suggestion:  Make it so it keeps attempting to travel to a congested server.

### ISSUE THREAD

**Issue by aaceace** [NightmareXIV/Lifestream#53]
As you know traveling to a busy server like balmung for example its constantly blocked for travelers even if you're in the same data center. Right now the only way to travel to a locked server as a traveller is to keep spamming in hopes that you can get in. Its doable but its tedius to go through all the menus. I was wondering if you could make it so lifestream would keep attempting to travel even after getting the "This world is experiencing congestion. Characters from other worlds cannot visit at this time." error   It would be nice if square would just let us enter a queue but they don't let travelers queue up. anyway just a suggestion.

**Comment by Limiana** [comment]
Hello!
This feature is already in testing version of the plugin. You will need to enable it in settings, however
