### ISSUE TITLE
[Feature request] Ability to edit priority for /li auto

### ISSUE THREAD

**Issue by alyssadev** [NightmareXIV/Lifestream#54]
Currently, priority order is private/fc/apartment (/inn in testing). Request is to add the ability to change this priority, or otherwise set the destination for /li auto.

**Comment by Limiana** [comment]
Hello!
You can edit priority in testing
![image](https://github.com/user-attachments/assets/3e7068c3-bd38-4e01-afb7-1d8f47e90cc3)

**Comment by alyssadev** [comment]
Thank you!
