### ISSUE TITLE
[Bug] Cannot enter to apartment

### ISSUE THREAD

**Issue by chenjr0719** [NightmareXIV/Lifestream#61]
When using `/li apt`, my character will teleport in front of the apartment, walk to the entrance of the apartment and just stuck. Looks like it is waiting for some task to be complete

Logs:
```
> [2024/9/14 下午 08:20:37 +08:00] [NeoTaskManager] →Starting to execute task [GoToMyApartment], timeout=30000
> [2024/9/14 下午 08:21:07 +08:00] [NeoTaskManager] →→Task timed out GoToMyApartment
> [2024/9/14 下午 08:21:07 +08:00] Exception of type 'ECommons.Automation.NeoTaskManager.TaskTimeoutException' was thrown.
   at ECommons.Automation.NeoTaskManager.TaskManager.Tick(Object framework) in D:\VS\Lifestream\ECommons\ECommons\Automation\NeoTaskManager\TaskManager.cs:line 167
```

Is that related to this line? My client language is Japanse and it might be missed here:
https://github.com/NightmareXIV/Lifestream/blob/9a1be5c50f4b20888b0a7d831cf815c48ade37d9/Lifestream/Lang.cs#L72

The line in Japanese is `自分の部屋に移動する`.

**Comment by Limiana** [comment]
Should be fixed in testing 2.3.0.0 update
