### ISSUE TITLE
Character not found

### ISSUE THREAD

**Issue by TentouXIV** [NightmareXIV/Lifestream#67]
When trying it in the character selection to go to another world server, it can't find my character for some reason

**Comment by Limiana** [comment]
Hello. Uhh, what?
I mean, this doesn't appears to be Lifestream issue. Please log in to your [Lodestone](https://na.finalfantasyxiv.com/lodestone/), and overview your character list to confirm where they are created

**Comment by TentouXIV** [comment]
Hi @Limiana Started to work after I updated to the release branch, going to close this issue.
